import { ItemDef } from '../types/game';

export const ITEMS_DATABASE: Record<string, ItemDef> = {
  // --- WEAPONS ---
  sword_iron: {
    id: 'sword_iron',
    name: 'Iron Sword',
    rarity: 'common',
    type: 'weapon',
    slot: 'weapon',
    icon: 'Sword',
    iconPath: '/game-assets/items/weapons/sword_weapons/3264_sword.png',
    attack: 14,
    defense: 10,
    price: 35,
    description: 'A sturdy hand-crafted blade forged in the smithies of Thais.',
    reqVocation: ['KNIGHT'],
  },
  sword_broadsword: {
    id: 'sword_broadsword',
    name: 'Broadsword',
    rarity: 'common',
    type: 'weapon',
    slot: 'weapon',
    icon: 'Sword',
    iconPath: '/game-assets/items/weapons/sword_weapons/3301_broadsword.png',
    attack: 26,
    defense: 18,
    reqLevel: 8,
    price: 150,
    description: 'A heavy double-edged broadsword.',
    reqVocation: ['KNIGHT'],
  },
  sword_bright: {
    id: 'sword_bright',
    name: 'Bright Sword',
    rarity: 'rare',
    type: 'weapon',
    slot: 'weapon',
    icon: 'Sparkles',
    iconPath: '/game-assets/items/weapons/sword_weapons/3295_bright_sword.png',
    attack: 36,
    defense: 30,
    reqLevel: 20,
    price: 1200,
    description: 'Emits a soothing luminous aura. Masterwork blade with incredible balance.',
    reqVocation: ['KNIGHT'],
  },
  sword_fire: {
    id: 'sword_fire',
    name: 'Fire Sword',
    rarity: 'unique',
    type: 'weapon',
    slot: 'weapon',
    icon: 'Flame',
    iconPath: '/game-assets/items/weapons/sword_weapons/3280_fire_sword.png',
    attack: 45,
    defense: 24,
    reqLevel: 30,
    price: 4500,
    description: 'Infused with the eternal flame of the ancient dragon lairs.',
    reqVocation: ['KNIGHT'],
  },
  bow_wooden: {
    id: 'bow_wooden',
    name: 'Hunting Bow',
    rarity: 'common',
    type: 'weapon',
    slot: 'weapon',
    icon: 'Crosshair',
    iconPath: '/game-assets/items/weapons/distance_weapons/12733_shimmer_bow.png',
    attack: 16,
    defense: 6,
    price: 40,
    description: 'A flexible yew bow crafted for distance hunters.',
    reqVocation: ['PALADIN'],
  },
  crossbow_iron: {
    id: 'crossbow_iron',
    name: 'Iron Crossbow',
    rarity: 'rare',
    type: 'weapon',
    slot: 'weapon',
    icon: 'Crosshair',
    iconPath: '/game-assets/items/weapons/distance_weapons/14247_ornate_crossbow.png',
    attack: 32,
    defense: 8,
    reqLevel: 15,
    price: 800,
    description: 'A sturdy iron crossbow for hunting large game.',
    reqVocation: ['PALADIN'],
  },
  arbalest_royal: {
    id: 'arbalest_royal',
    name: 'Royal Arbalest',
    rarity: 'unique',
    type: 'weapon',
    slot: 'weapon',
    icon: 'Zap',
    iconPath: '/game-assets/items/weapons/distance_weapons/5803_arbalest.png',
    attack: 48,
    defense: 14,
    reqLevel: 28,
    price: 4800,
    description: 'An ornate weapon granted to champion Paladins of the Royal Guard.',
    reqVocation: ['PALADIN'],
  },
  wand_vortex: {
    id: 'wand_vortex',
    name: 'Wand of Vortex',
    rarity: 'common',
    type: 'weapon',
    slot: 'weapon',
    icon: 'Wand',
    iconPath: '/game-assets/items/weapons/wands/3074_wand_of_vortex.png',
    attack: 13,
    magicBoost: 1,
    price: 45,
    description: 'Shoots concentrated bolts of energy sparks.',
    reqVocation: ['SORCERER'],
  },
  wand_cosmic: {
    id: 'wand_cosmic',
    name: 'Wand of Cosmic Energy',
    rarity: 'rare',
    type: 'weapon',
    slot: 'weapon',
    icon: 'Wand2',
    iconPath: '/game-assets/items/weapons/wands/3073_wand_of_cosmic_energy.png',
    attack: 28,
    magicBoost: 3,
    reqLevel: 18,
    price: 1100,
    description: 'Crackles with astral power, channeling the cosmos.',
    reqVocation: ['SORCERER'],
  },
  rod_snakebite: {
    id: 'rod_snakebite',
    name: 'Snakebite Rod',
    rarity: 'common',
    type: 'weapon',
    slot: 'weapon',
    icon: 'Wand',
    iconPath: '/game-assets/items/weapons/rods/3066_snakebite_rod.png',
    attack: 13,
    magicBoost: 1,
    price: 45,
    description: 'Infused with earth venom by nature druids.',
    reqVocation: ['DRUID'],
  },
  rod_northwind: {
    id: 'rod_northwind',
    name: 'Northwind Rod',
    rarity: 'rare',
    type: 'weapon',
    slot: 'weapon',
    icon: 'Wand2',
    iconPath: '/game-assets/items/weapons/rods/8083_northwind_rod.png',
    attack: 28,
    magicBoost: 3,
    reqLevel: 18,
    price: 1100,
    description: 'Summons freezing blizzards from Svargrond.',
    reqVocation: ['DRUID'],
  },

  // --- SHIELDS ---
  shield_wooden: {
    id: 'shield_wooden',
    name: 'Wooden Shield',
    rarity: 'common',
    type: 'shield',
    slot: 'shield',
    icon: 'Shield',
    iconPath: '/game-assets/items/equipment/shields/3412_wooden_shield.png',
    defense: 15,
    price: 25,
    description: 'Simple planks bound with iron rivets.',
  },
  shield_dwarven: {
    id: 'shield_dwarven',
    name: 'Dwarven Shield',
    rarity: 'common',
    type: 'shield',
    slot: 'shield',
    icon: 'ShieldAlert',
    iconPath: '/game-assets/items/equipment/shields/3425_dwarven_shield.png',
    defense: 26,
    reqLevel: 10,
    price: 220,
    description: 'Forged in Kazordoon from deep granite steel.',
  },
  shield_guardian: {
    id: 'shield_guardian',
    name: 'Guardian Shield',
    rarity: 'rare',
    type: 'shield',
    slot: 'shield',
    icon: 'ShieldCheck',
    iconPath: '/game-assets/items/equipment/shields/3415_guardian_shield.png',
    defense: 34,
    reqLevel: 20,
    price: 1250,
    description: 'Carried by ancient temple protectors.',
  },
  shield_demon: {
    id: 'shield_demon',
    name: 'Demon Shield',
    rarity: 'unique',
    type: 'shield',
    slot: 'shield',
    icon: 'ShieldAlert',
    iconPath: '/game-assets/items/equipment/shields/3420_demon_shield.png',
    defense: 42,
    reqLevel: 32,
    price: 5200,
    description: 'Imbued with hellish fortitude. Incredibly light yet impenetrable.',
  },

  // --- ARMOR ---
  armor_leather: {
    id: 'armor_leather',
    name: 'Leather Armor',
    rarity: 'common',
    type: 'armor',
    slot: 'armor',
    icon: 'Shirt',
    iconPath: '/game-assets/items/equipment/armors/3361_leather_armor.png',
    armor: 4,
    price: 20,
    description: 'Supple boiled leather armor.',
  },
  armor_plate: {
    id: 'armor_plate',
    name: 'Plate Armor',
    rarity: 'common',
    type: 'armor',
    slot: 'armor',
    icon: 'Shield',
    iconPath: '/game-assets/items/equipment/armors/3357_plate_armor.png',
    armor: 10,
    price: 180,
    description: 'Solid interlocking steel plates.',
  },
  armor_knight: {
    id: 'armor_knight',
    name: 'Knight Armor',
    rarity: 'rare',
    type: 'armor',
    slot: 'armor',
    icon: 'ShieldCheck',
    iconPath: '/game-assets/items/equipment/armors/3370_knight_armor.png',
    armor: 13,
    reqLevel: 18,
    price: 950,
    description: 'Standard issue high-grade armor of Thais knighthood.',
  },
  armor_magic_plate: {
    id: 'armor_magic_plate',
    name: 'Magic Plate Armor',
    rarity: 'unique',
    type: 'armor',
    slot: 'armor',
    icon: 'Award',
    iconPath: '/game-assets/items/equipment/armors/3366_magic_plate_armor.png',
    armor: 17,
    magicBoost: 2,
    reqLevel: 30,
    price: 6000,
    description: 'The legendary MPA! Glows with ancient runic energy.',
  },

  // --- HELMETS ---
  helmet_leather: {
    id: 'helmet_leather',
    name: 'Leather Helmet',
    rarity: 'common',
    type: 'helmet',
    slot: 'helmet',
    icon: 'Crown',
    iconPath: '/game-assets/items/equipment/helmets/3355_leather_helmet.png',
    armor: 2,
    price: 15,
    description: 'Basic head protection against bites and scratches.',
  },
  helmet_iron: {
    id: 'helmet_iron',
    name: 'Iron Helmet',
    rarity: 'common',
    type: 'helmet',
    slot: 'helmet',
    icon: 'Crown',
    iconPath: '/game-assets/items/equipment/helmets/3353_iron_helmet.png',
    armor: 5,
    price: 80,
    description: 'Enclosed nasal helmet forged from pig iron.',
  },
  helmet_crusader: {
    id: 'helmet_crusader',
    name: 'Crusader Helmet',
    rarity: 'rare',
    type: 'helmet',
    slot: 'helmet',
    icon: 'Crown',
    iconPath: '/game-assets/items/equipment/helmets/3391_crusader_helmet.png',
    armor: 8,
    reqLevel: 22,
    price: 980,
    description: 'A great winged helm worn by holy knights.',
  },
  helmet_royal: {
    id: 'helmet_royal',
    name: 'Royal Helmet',
    rarity: 'unique',
    type: 'helmet',
    slot: 'helmet',
    icon: 'Crown',
    iconPath: '/game-assets/items/equipment/helmets/3392_royal_helmet.png',
    armor: 11,
    reqLevel: 32,
    price: 4500,
    description: 'Crafted for royalty with inlaid ruby runes.',
  },

  // --- LEGS & BOOTS ---
  legs_leather: {
    id: 'legs_leather',
    name: 'Leather Legs',
    rarity: 'common',
    type: 'legs',
    slot: 'legs',
    icon: 'Footprints',
    iconPath: '/game-assets/items/equipment/legs/3559_leather_legs.png',
    armor: 2,
    price: 18,
    description: 'Tanned hide breeches.',
  },
  legs_plate: {
    id: 'legs_plate',
    name: 'Plate Legs',
    rarity: 'common',
    type: 'legs',
    slot: 'legs',
    icon: 'Shield',
    iconPath: '/game-assets/items/equipment/legs/3557_plate_legs.png',
    armor: 7,
    price: 140,
    description: 'Greaves made of riveted iron strips.',
  },
  legs_knight: {
    id: 'legs_knight',
    name: 'Knight Legs',
    rarity: 'rare',
    type: 'legs',
    slot: 'legs',
    icon: 'ShieldCheck',
    iconPath: '/game-assets/items/equipment/legs/3371_knight_legs.png',
    armor: 9,
    reqLevel: 20,
    price: 880,
    description: 'Finely honed knightly leg guards.',
  },
  boots_leather: {
    id: 'boots_leather',
    name: 'Leather Boots',
    rarity: 'common',
    type: 'boots',
    slot: 'boots',
    icon: 'Footprints',
    iconPath: '/game-assets/items/equipment/boots/3552_leather_boots.png',
    armor: 1,
    price: 15,
    description: 'Basic walking boots.',
  },
  boots_haste: {
    id: 'boots_haste',
    name: 'Boots of Haste (BoH)',
    rarity: 'unique',
    type: 'boots',
    slot: 'boots',
    icon: 'Zap',
    iconPath: '/game-assets/items/equipment/boots/3079_boots_of_haste.png',
    armor: 3,
    reqLevel: 20,
    price: 3200,
    description: 'Infuses the wearer with incredible agility and swift strides!',
  },

  // --- AMULETS & RINGS ---
  amulet_platinum: {
    id: 'amulet_platinum',
    name: 'Platinum Amulet',
    rarity: 'rare',
    type: 'amulet',
    slot: 'amulet',
    icon: 'Gem',
    iconPath: '/game-assets/items/equipment/amulets_and_necklaces/3055_platinum_amulet.png',
    armor: 2,
    defense: 4,
    price: 750,
    description: 'Polished platinum talisman that wards off physical harm.',
  },
  ring_life: {
    id: 'ring_life',
    name: 'Life Ring',
    rarity: 'rare',
    type: 'ring',
    slot: 'ring',
    icon: 'CircleDot',
    iconPath: '/game-assets/items/equipment/rings/3052_life_ring.png',
    magicBoost: 1,
    price: 600,
    description: 'Accelerates health and mana regeneration while equipped.',
  },

  // --- POTIONS & CONSUMABLES ---
  potion_health: {
    id: 'potion_health',
    name: 'Health Potion',
    rarity: 'common',
    type: 'potion',
    icon: 'HeartPulse',
    iconPath: '/game-assets/items/frames/health_potion/frame_0.png',
    healthRestore: 120,
    price: 25,
    description: 'Restores 120 HP instantaneously.',
    stackable: true,
  },
  potion_mana: {
    id: 'potion_mana',
    name: 'Mana Potion',
    rarity: 'common',
    type: 'potion',
    icon: 'Droplet',
    iconPath: '/game-assets/items/frames/mana_potion/frame_0.png',
    manaRestore: 100,
    price: 30,
    description: 'Restores 100 Mana points instantaneously.',
    stackable: true,
  },
  potion_strong_health: {
    id: 'potion_strong_health',
    name: 'Strong Health Potion',
    rarity: 'rare',
    type: 'potion',
    icon: 'HeartPulse',
    iconPath: '/game-assets/items/frames/strong_health_potion/frame_0.png',
    healthRestore: 300,
    price: 80,
    description: 'Restores 300 HP instantaneously.',
    stackable: true,
  },

  // --- VALUABLES & JUNK ---
  val_torch: {
    id: 'val_torch',
    name: 'Adventurer Torch',
    rarity: 'common',
    type: 'valuable',
    icon: 'Flame',
    iconPath: '/game-assets/items/frames/lit_torch/frame_0.png',
    price: 5,
    description: 'Keeps dark dungeon passages brightly illuminated.',
    stackable: true,
  },
  val_rotworm_meat: {
    id: 'val_rotworm_meat',
    name: 'Rotworm Meat',
    rarity: 'common',
    type: 'valuable',
    icon: 'Drumstick',
    iconPath: '/game-assets/items/frames/meat/frame_0.png',
    price: 6,
    description: 'Juicy if somewhat foul-smelling subterranean meat.',
    stackable: true,
  },
  val_cyclops_toe: {
    id: 'val_cyclops_toe',
    name: 'Cyclops Toe',
    rarity: 'rare',
    type: 'valuable',
    icon: 'Bone',
    iconPath: '/game-assets/items/frames/cyclops_toe/frame_0.png',
    price: 65,
    description: 'A grim hunting trophy collected from Mount Sternum.',
    stackable: true,
  },
  val_queen_mandible: {
    id: 'val_queen_mandible',
    name: 'Queen Mandible',
    rarity: 'unique',
    type: 'valuable',
    icon: 'Sparkles',
    iconPath: '/game-assets/items/frames/widow_s_mandibles/frame_0.png',
    price: 450,
    description: 'The golden glowing horn harvested from the Rotworm Queen.',
    stackable: true,
  },
  bp_brown: {
    id: 'bp_brown',
    name: 'Backpack',
    rarity: 'common',
    type: 'valuable',
    slot: 'backpack',
    icon: 'Package',
    iconPath: '/game-assets/items/frames/backpack/frame_0.png',
    price: 20,
    description: 'Holds up to 20 different items and gold.',
  },
};
