import { MapHuntDef } from '../types/game';

export const MAPS_DATABASE: Record<string, MapHuntDef> = {
  HUB_THAIS: {
    id: 'HUB_THAIS',
    name: 'Santuário de Thais (Praça Sagrada)',
    description: 'Santuário celestial a céu aberto. Desfrute da praça com fontes cristalinas, jardins de ciprestes, bonecos de treino no pátio e o Altar Sagrado de restauração.',
    isSafeZone: true,
    mapType: 'sanctuary',
    recommendedLevel: 1,
    theme: 'thais_temple',
    gridSize: { width: 22, height: 22 },
    musicMood: 'peaceful',
    maxMonsters: 0,
    monsterSpawnPool: [],
  },

  // ==========================================
  // 1. HUNTS COMUNS (MUNDO ABERTO - MAPAS ESTÁTICOS & RESPAWN CONTÍNUO)
  // ==========================================
  HUNT_SEWERS: {
    id: 'HUNT_SEWERS',
    name: 'Esgotos Antigos de Thais',
    description: 'Cavernas úmidas com layout estático e respawn perpétuo de Cave Rats, Rotworms e Carrion Worms. Ideal para grind estável inicial.',
    isSafeZone: false,
    mapType: 'open_world',
    recommendedLevel: 1,
    theme: 'catacombs',
    gridSize: { width: 32, height: 32 },
    musicMood: 'dungeon',
    maxMonsters: 14,
    bossMonsterId: 'rotworm_queen',
    monsterSpawnPool: [
      { monsterId: 'cave_rat', weight: 40 },
      { monsterId: 'rotworm', weight: 45 },
      { monsterId: 'carrion_worm', weight: 15 },
    ],
  },
  HUNT_RUINS: {
    id: 'HUNT_RUINS',
    name: 'Planície & Ruínas de Sternum',
    description: 'Cordilheira rochosa com layout fixo e caminhos conhecidos, habitada por hordas de Skeletons e Ciclopes em respawn contínuo.',
    isSafeZone: false,
    mapType: 'open_world',
    recommendedLevel: 8,
    theme: 'ruins',
    gridSize: { width: 34, height: 34 },
    musicMood: 'ruins',
    maxMonsters: 14,
    bossMonsterId: 'cyclops_smith',
    monsterSpawnPool: [
      { monsterId: 'skeleton', weight: 45 },
      { monsterId: 'cyclops', weight: 55 },
    ],
  },
  HUNT_PIRATE_COVE: {
    id: 'HUNT_PIRATE_COVE',
    name: 'Enseada dos Piratas de Liberty Bay',
    description: 'Costa e cavernas litorâneas fixas com patrulhas contínuas de Corsários e Piratas saqueadores.',
    isSafeZone: false,
    mapType: 'open_world',
    recommendedLevel: 16,
    theme: 'catacombs',
    gridSize: { width: 34, height: 34 },
    musicMood: 'dungeon',
    maxMonsters: 14,
    bossMonsterId: 'pirate_captain',
    monsterSpawnPool: [
      { monsterId: 'pirate_cutthroat', weight: 50 },
      { monsterId: 'pirate_corsair', weight: 50 },
    ],
  },
  HUNT_DRAGON_LAIR: {
    id: 'HUNT_DRAGON_LAIR',
    name: 'Covil dos Dragões de Ankrahmun',
    description: 'Salões vulcânicos e corredores de pedra estáticos com ninhos de Dragon Hatchlings e Dragões adultos.',
    isSafeZone: false,
    mapType: 'open_world',
    recommendedLevel: 25,
    theme: 'ruins',
    gridSize: { width: 36, height: 36 },
    musicMood: 'ruins',
    maxMonsters: 14,
    bossMonsterId: 'dragon_lord',
    monsterSpawnPool: [
      { monsterId: 'dragon_hatchling', weight: 40 },
      { monsterId: 'dragon', weight: 60 },
    ],
  },
  HUNT_HERO_CAVE: {
    id: 'HUNT_HERO_CAVE',
    name: 'Santuário dos Heróis de Edron',
    description: 'Salões ancestrais com arquitetura gótica e câmaras de caça fixa guardadas por Sacerdotisas e Cavaleiros Negros.',
    isSafeZone: false,
    mapType: 'open_world',
    recommendedLevel: 35,
    theme: 'catacombs',
    gridSize: { width: 36, height: 36 },
    musicMood: 'dungeon',
    maxMonsters: 14,
    bossMonsterId: 'hero_champion',
    monsterSpawnPool: [
      { monsterId: 'priestess', weight: 45 },
      { monsterId: 'black_knight', weight: 55 },
    ],
  },
  HUNT_DEMON_HELL: {
    id: 'HUNT_DEMON_HELL',
    name: 'Fornalha Demoníaca de Goroma',
    description: 'Vales de lava e granito com rotas clássicas de caça, habitados por Fire Devils e colossais Behemoths em fluxo perpétuo.',
    isSafeZone: false,
    mapType: 'open_world',
    recommendedLevel: 50,
    theme: 'ruins',
    gridSize: { width: 38, height: 38 },
    musicMood: 'ruins',
    maxMonsters: 15,
    bossMonsterId: 'demon_overlord',
    monsterSpawnPool: [
      { monsterId: 'fire_devil', weight: 40 },
      { monsterId: 'behemoth', weight: 60 },
    ],
  },

  // ==========================================
  // 2. DUNGEONS PROCEDURAIS (MASMORRAS INSTANCIADAS POR ANDARES B1, B2... & CHEFES)
  // ==========================================
  DUNGEON_CATACOMBS: {
    id: 'DUNGEON_CATACOMBS',
    name: 'Catacumbas Esquecidas (Dungeon B1+)',
    description: 'Masmorra procedural com labirintos gerados aleatoriamente, baús secretos, armadilhas mortais, ondas de monstros e Chefe de Andar.',
    isSafeZone: false,
    mapType: 'dungeon',
    recommendedLevel: 10,
    theme: 'catacombs',
    gridSize: { width: 34, height: 34 },
    musicMood: 'dungeon',
    maxMonsters: 14,
    bossMonsterId: 'rotworm_queen',
    monsterSpawnPool: [
      { monsterId: 'cave_rat', weight: 30 },
      { monsterId: 'rotworm', weight: 45 },
      { monsterId: 'carrion_worm', weight: 25 },
    ],
  },
  DUNGEON_ABYSSAL_RUINS: {
    id: 'DUNGEON_ABYSSAL_RUINS',
    name: 'Cidadela Abissal (Dungeon B1+)',
    description: 'Expedição procedural por andares mais profundos. Modificadores dinâmicos de dano e loot, câmaras de tesouros e o temível Ferreiro Ciclope.',
    isSafeZone: false,
    mapType: 'dungeon',
    recommendedLevel: 22,
    theme: 'ruins',
    gridSize: { width: 36, height: 36 },
    musicMood: 'ruins',
    maxMonsters: 15,
    bossMonsterId: 'cyclops_smith',
    monsterSpawnPool: [
      { monsterId: 'skeleton', weight: 40 },
      { monsterId: 'cyclops', weight: 60 },
    ],
  },
  DUNGEON_DRAGON_SPIRE: {
    id: 'DUNGEON_DRAGON_SPIRE',
    name: 'Pináculo do Dragão Ancião (Dungeon B1+)',
    description: 'Labirinto vertical gerado na rocha vulcânica com urnas de cristal, hazards de fogo e o lendário Dragon Lord aguardando no portal.',
    isSafeZone: false,
    mapType: 'dungeon',
    recommendedLevel: 38,
    theme: 'ruins',
    gridSize: { width: 38, height: 38 },
    musicMood: 'ruins',
    maxMonsters: 16,
    bossMonsterId: 'dragon_lord',
    monsterSpawnPool: [
      { monsterId: 'dragon_hatchling', weight: 35 },
      { monsterId: 'dragon', weight: 65 },
    ],
  },
  DUNGEON_INFERNAL_VAULT: {
    id: 'DUNGEON_INFERNAL_VAULT',
    name: 'Cofre Infernal do Pesadelo (Dungeon B1+)',
    description: 'A masmorra mais letal do continente. Andares impiedosos com affixes de elite, quebravéis raros e o confronto com o Lorde Demônio Supremo.',
    isSafeZone: false,
    mapType: 'dungeon',
    recommendedLevel: 55,
    theme: 'ruins',
    gridSize: { width: 40, height: 40 },
    musicMood: 'ruins',
    maxMonsters: 18,
    bossMonsterId: 'demon_overlord',
    monsterSpawnPool: [
      { monsterId: 'fire_devil', weight: 35 },
      { monsterId: 'behemoth', weight: 65 },
    ],
  },

  // ==========================================
  // 3. RIFT TOWER (FENDAS TEMPORIZADAS & AÇÃO LIVRE ESTILO DIABLO)
  // ==========================================
  RIFT_TOWER_FLOOR_1: {
    id: 'RIFT_TOWER_FLOOR_1',
    name: 'Fenda Maior: Andar 1 - Catacumbas das Fendas',
    description: 'Fenda de densidade acelerada. Derrote as hordas no tempo limite com movimentação 360° fluida para invocar o Guardião da Fenda.',
    isSafeZone: false,
    mapType: 'rift',
    movementMode: 'free_action',
    recommendedLevel: 15,
    riftFloor: 1,
    theme: 'catacombs',
    gridSize: { width: 36, height: 36 },
    musicMood: 'dungeon',
    maxMonsters: 22,
    bossMonsterId: 'rotworm_queen',
    specialRewards: ['Gema de Maestria Comum', 'Pedras de Encantamento +1', 'Caixa de Ouro Rápido'],
    monsterSpawnPool: [
      { monsterId: 'cave_rat', weight: 25 },
      { monsterId: 'rotworm', weight: 45 },
      { monsterId: 'skeleton', weight: 30 },
    ],
  },
  RIFT_TOWER_FLOOR_10: {
    id: 'RIFT_TOWER_FLOOR_10',
    name: 'Fenda Maior: Andar 10 - Abismo Sombrio',
    description: 'Hordas de corsários e ciclopes mutantes. Otimize seu DPS em área e desvie dos golpes pesados com esquiva contínua.',
    isSafeZone: false,
    mapType: 'rift',
    movementMode: 'free_action',
    recommendedLevel: 30,
    riftFloor: 10,
    theme: 'ruins',
    gridSize: { width: 38, height: 38 },
    musicMood: 'ruins',
    maxMonsters: 24,
    bossMonsterId: 'cyclops_smith',
    specialRewards: ['Gema Rara de Crítico', 'Fragmentos de Refino', 'Equipamento Nobre'],
    monsterSpawnPool: [
      { monsterId: 'pirate_corsair', weight: 35 },
      { monsterId: 'cyclops', weight: 45 },
      { monsterId: 'priestess', weight: 20 },
    ],
  },
  RIFT_TOWER_FLOOR_25: {
    id: 'RIFT_TOWER_FLOOR_25',
    name: 'Fenda Maior: Andar 25 - Vórtice dos Dragões',
    description: 'Densidade extrema de fogo e dragões alados. O Guardião do Fogo exige rotação ágil e ataques telegrafados.',
    isSafeZone: false,
    mapType: 'rift',
    movementMode: 'free_action',
    recommendedLevel: 45,
    riftFloor: 25,
    theme: 'ruins',
    gridSize: { width: 40, height: 40 },
    musicMood: 'ruins',
    maxMonsters: 26,
    bossMonsterId: 'dragon_lord',
    specialRewards: ['Gema Épica Elemental', 'Runas de Poder Supremo', 'Armaduras Raras'],
    monsterSpawnPool: [
      { monsterId: 'dragon_hatchling', weight: 30 },
      { monsterId: 'dragon', weight: 40 },
      { monsterId: 'black_knight', weight: 30 },
    ],
  },
  RIFT_TOWER_FLOOR_50: {
    id: 'RIFT_TOWER_FLOOR_50',
    name: 'Fenda Maior: Andar 50 - Domínio Celestial do Caos',
    description: 'O topo da Torre das Fendas. Hordas impiedosas com afixos devastadores e Guardião Colossal no limite dos 5 minutos.',
    isSafeZone: false,
    mapType: 'rift',
    movementMode: 'free_action',
    recommendedLevel: 65,
    riftFloor: 50,
    theme: 'ruins',
    gridSize: { width: 42, height: 42 },
    musicMood: 'ruins',
    maxMonsters: 28,
    bossMonsterId: 'demon_overlord',
    specialRewards: ['Gema Lendária Primal', 'Pergaminho de Encantamento Divino', 'Artefato Único'],
    monsterSpawnPool: [
      { monsterId: 'fire_devil', weight: 30 },
      { monsterId: 'behemoth', weight: 45 },
      { monsterId: 'black_knight', weight: 25 },
    ],
  },

  // ==========================================
  // 4. WORLD BOSSES (ARENAS ÉPICAS DE INCURSÃO & TELEGRAPHS DE ÁREA)
  // ==========================================
  WORLD_BOSS_MORGAROTH: {
    id: 'WORLD_BOSS_MORGAROTH',
    name: 'Arena do Pavor: Morgaroth',
    description: 'Confronte o Arquiteto do Pavor em sua arena vulcânica. Desvie dos círculos vermelhos de meteoros e ondas de choque em tempo real.',
    isSafeZone: false,
    mapType: 'world_boss',
    movementMode: 'free_action',
    recommendedLevel: 40,
    theme: 'ruins',
    gridSize: { width: 34, height: 34 },
    musicMood: 'ruins',
    maxMonsters: 4,
    bossMonsterId: 'morgaroth_lord',
    bossMechanics: [
      'Meteoro Telegrafado: Saia do círculo de impacto vermelho em 2.5s',
      'Onda Sísmica AoE: Cone de dano frontal de alta destruição',
      'Fase de Fúria: Ganha 30% de velocidade e dano ao chegar em 25% HP',
    ],
    elementalWeakness: 'Gelo & Sagrado',
    specialRewards: ['Magic Plate Armor', 'Demon Shield', 'Fire Sword', 'Amulet of Platinum'],
    monsterSpawnPool: [
      { monsterId: 'fire_devil', weight: 100 },
    ],
  },
  WORLD_BOSS_GHAZBARAN: {
    id: 'WORLD_BOSS_GHAZBARAN',
    name: 'Cúpula Glacial: Ghazbaran',
    description: 'O Demônio dos Gelos conjura tempestades de neve e estilhaços de gelo absolutos. Requer movimentação circular contínua.',
    isSafeZone: false,
    mapType: 'world_boss',
    movementMode: 'free_action',
    recommendedLevel: 55,
    theme: 'catacombs',
    gridSize: { width: 34, height: 34 },
    musicMood: 'dungeon',
    maxMonsters: 4,
    bossMonsterId: 'ghazbaran_frozen',
    bossMechanics: [
      'Nova de Congelamento: Área circular concêntrica em torno do Boss',
      'Estilhaços Glaciais: Linhas de projéteis telegrafadas no chão',
      'Prisão de Gelo: Congele se permanecer imóvel por mais de 3 segundos',
    ],
    elementalWeakness: 'Fogo & Energia',
    specialRewards: ['Boots of Haste Mágicas', 'Demon Shield Ancestral', 'Anéis da Vida Supremos'],
    monsterSpawnPool: [
      { monsterId: 'skeleton', weight: 100 },
    ],
  },
  WORLD_BOSS_FERUMBRAS: {
    id: 'WORLD_BOSS_FERUMBRAS',
    name: 'Torre Proibida: Ferumbras Ascendente',
    description: 'A maior lenda do continente. O arquimago canaliza tempestades elétricas apocalípticas e barreiras de fogo negro.',
    isSafeZone: false,
    mapType: 'world_boss',
    movementMode: 'free_action',
    recommendedLevel: 70,
    theme: 'ruins',
    gridSize: { width: 36, height: 36 },
    musicMood: 'ruins',
    maxMonsters: 4,
    bossMonsterId: 'ferumbras_ascendant',
    bossMechanics: [
      'Tempestade Apocalíptica: Pilares de raios roxos pipocam na arena inteira',
      'Raio Concentrado: Feixe de energia cósmica teleguiado de longo alcance',
      'Barreira de Fogo Negro: Invoca lacaios demoníacos nos 50% de HP',
    ],
    elementalWeakness: 'Dano Físico Puro & Sagrado',
    specialRewards: ['Wand Cósmica de Ferumbras', 'Magic Plate Armor +5', 'Título Mítico de Matador de Arquimago'],
    monsterSpawnPool: [
      { monsterId: 'priestess', weight: 50 },
      { monsterId: 'black_knight', weight: 50 },
    ],
  },
};

