import { MonsterDef } from '../types/game';

export const MONSTERS_DATABASE: Record<string, MonsterDef> = {
  // --- HUNT 1: SEWERS / CATACOMBS ---
  cave_rat: {
    id: 'cave_rat',
    name: 'Cave Rat',
    maxHp: 35,
    attack: 8,
    defense: 4,
    armor: 2,
    speed: 2.2,
    exp: 20,
    modelType: 'cave_rat',
    size: 0.7,
    color: '#78350f',
    goldMin: 2,
    goldMax: 8,
    lootTable: [
      { defId: 'val_torch', chance: 0.35, minCount: 1, maxCount: 1 },
      { defId: 'potion_health', chance: 0.15, minCount: 1, maxCount: 1 },
      { defId: 'helmet_leather', chance: 0.1, minCount: 1, maxCount: 1 },
    ],
  },
  rotworm: {
    id: 'rotworm',
    name: 'Rotworm',
    maxHp: 65,
    attack: 17,
    defense: 8,
    armor: 4,
    speed: 1.8,
    exp: 40,
    modelType: 'rotworm',
    size: 1.0,
    color: '#b45309',
    goldMin: 5,
    goldMax: 20,
    lootTable: [
      { defId: 'val_rotworm_meat', chance: 0.7, minCount: 1, maxCount: 2 },
      { defId: 'shield_wooden', chance: 0.25, minCount: 1, maxCount: 1 },
      { defId: 'sword_iron', chance: 0.2, minCount: 1, maxCount: 1 },
      { defId: 'potion_health', chance: 0.3, minCount: 1, maxCount: 2 },
    ],
  },
  carrion_worm: {
    id: 'carrion_worm',
    name: 'Carrion Worm',
    maxHp: 145,
    attack: 28,
    defense: 14,
    armor: 8,
    speed: 1.9,
    exp: 75,
    modelType: 'carrion_worm',
    size: 1.3,
    color: '#92400e',
    goldMin: 12,
    goldMax: 38,
    lootTable: [
      { defId: 'val_rotworm_meat', chance: 0.8, minCount: 1, maxCount: 3 },
      { defId: 'shield_dwarven', chance: 0.15, minCount: 1, maxCount: 1 },
      { defId: 'armor_plate', chance: 0.12, minCount: 1, maxCount: 1 },
      { defId: 'potion_strong_health', chance: 0.2, minCount: 1, maxCount: 1 },
    ],
    spells: [
      { name: 'Poison Spit', chance: 0.2, damage: 22, color: '#22c55e' },
    ],
  },

  // BOSS 1: Rotworm Queen
  rotworm_queen: {
    id: 'rotworm_queen',
    name: 'Rotworm Queen',
    maxHp: 850,
    attack: 48,
    defense: 26,
    armor: 14,
    speed: 1.7,
    exp: 450,
    isBoss: true,
    modelType: 'rotworm_queen',
    size: 2.2,
    color: '#d97706',
    goldMin: 80,
    goldMax: 250,
    lootTable: [
      { defId: 'val_queen_mandible', chance: 1.0, minCount: 1, maxCount: 1 },
      { defId: 'shield_guardian', chance: 0.45, minCount: 1, maxCount: 1 },
      { defId: 'sword_bright', chance: 0.35, minCount: 1, maxCount: 1 },
      { defId: 'wand_cosmic', chance: 0.35, minCount: 1, maxCount: 1 },
      { defId: 'rod_northwind', chance: 0.35, minCount: 1, maxCount: 1 },
      { defId: 'ring_life', chance: 0.4, minCount: 1, maxCount: 1 },
      { defId: 'potion_strong_health', chance: 0.9, minCount: 2, maxCount: 5 },
    ],
    spells: [
      { name: 'Earth Tremor', chance: 0.25, damage: 45, color: '#ca8a04', isAoe: true },
      { name: 'Acidic Spray', chance: 0.2, damage: 35, color: '#84cc16' },
    ],
  },

  // --- HUNT 2: RUINS / MOUNT STERNUM ---
  skeleton: {
    id: 'skeleton',
    name: 'Skeleton Warrior',
    maxHp: 110,
    attack: 26,
    defense: 12,
    armor: 6,
    speed: 2.1,
    exp: 60,
    modelType: 'skeleton',
    size: 1.0,
    color: '#e2e8f0',
    goldMin: 10,
    goldMax: 30,
    lootTable: [
      { defId: 'helmet_iron', chance: 0.2, minCount: 1, maxCount: 1 },
      { defId: 'sword_broadsword', chance: 0.15, minCount: 1, maxCount: 1 },
      { defId: 'shield_wooden', chance: 0.3, minCount: 1, maxCount: 1 },
      { defId: 'potion_mana', chance: 0.25, minCount: 1, maxCount: 2 },
    ],
  },
  cyclops: {
    id: 'cyclops',
    name: 'Cyclops',
    maxHp: 260,
    attack: 52,
    defense: 22,
    armor: 12,
    speed: 1.8,
    exp: 150,
    modelType: 'cyclops',
    size: 1.6,
    color: '#f87171',
    goldMin: 25,
    goldMax: 70,
    lootTable: [
      { defId: 'val_cyclops_toe', chance: 0.5, minCount: 1, maxCount: 2 },
      { defId: 'legs_plate', chance: 0.2, minCount: 1, maxCount: 1 },
      { defId: 'helmet_crusader', chance: 0.12, minCount: 1, maxCount: 1 },
      { defId: 'potion_strong_health', chance: 0.35, minCount: 1, maxCount: 2 },
    ],
    spells: [
      { name: 'Boulder Throw', chance: 0.25, damage: 45, color: '#78716c' },
    ],
  },

  // BOSS 2: Cyclops Smith
  cyclops_smith: {
    id: 'cyclops_smith',
    name: 'Cyclops Smith',
    maxHp: 1650,
    attack: 85,
    defense: 36,
    armor: 20,
    speed: 1.85,
    exp: 950,
    isBoss: true,
    modelType: 'cyclops_smith',
    size: 2.4,
    color: '#ef4444',
    goldMin: 180,
    goldMax: 500,
    lootTable: [
      { defId: 'sword_fire', chance: 0.4, minCount: 1, maxCount: 1 },
      { defId: 'arbalest_royal', chance: 0.4, minCount: 1, maxCount: 1 },
      { defId: 'armor_magic_plate', chance: 0.25, minCount: 1, maxCount: 1 },
      { defId: 'boots_haste', chance: 0.35, minCount: 1, maxCount: 1 },
      { defId: 'shield_demon', chance: 0.3, minCount: 1, maxCount: 1 },
      { defId: 'amulet_platinum', chance: 0.6, minCount: 1, maxCount: 1 },
      { defId: 'potion_strong_health', chance: 1.0, minCount: 3, maxCount: 6 },
    ],
    spells: [
      { name: 'Molten Anvil Slam', chance: 0.3, damage: 85, color: '#ea580c', isAoe: true },
      { name: 'Smith Forge Sparks', chance: 0.25, damage: 60, color: '#f97316' },
    ],
  },

  // --- HUNT 3: PIRATE COVE ---
  pirate_cutthroat: {
    id: 'pirate_cutthroat',
    name: 'Pirate Cutthroat',
    maxHp: 195,
    attack: 38,
    defense: 18,
    armor: 10,
    speed: 2.15,
    exp: 110,
    modelType: 'pirate',
    size: 1.0,
    color: '#0284c7',
    goldMin: 20,
    goldMax: 60,
    lootTable: [
      { defId: 'sword_broadsword', chance: 0.25, minCount: 1, maxCount: 1 },
      { defId: 'helmet_iron', chance: 0.2, minCount: 1, maxCount: 1 },
      { defId: 'potion_health', chance: 0.4, minCount: 1, maxCount: 2 },
    ],
  },
  pirate_corsair: {
    id: 'pirate_corsair',
    name: 'Pirate Corsair',
    maxHp: 320,
    attack: 52,
    defense: 26,
    armor: 14,
    speed: 2.1,
    exp: 175,
    modelType: 'pirate',
    size: 1.1,
    color: '#0369a1',
    goldMin: 35,
    goldMax: 95,
    lootTable: [
      { defId: 'crossbow_iron', chance: 0.2, minCount: 1, maxCount: 1 },
      { defId: 'shield_dwarven', chance: 0.2, minCount: 1, maxCount: 1 },
      { defId: 'boots_leather', chance: 0.35, minCount: 1, maxCount: 1 },
      { defId: 'potion_mana', chance: 0.4, minCount: 1, maxCount: 2 },
    ],
    spells: [
      { name: 'Flintlock Shot', chance: 0.2, damage: 45, color: '#f59e0b' },
    ],
  },
  pirate_captain: {
    id: 'pirate_captain',
    name: 'Capitão Barba-Rubra',
    maxHp: 2200,
    attack: 95,
    defense: 42,
    armor: 22,
    speed: 2.0,
    exp: 1350,
    isBoss: true,
    modelType: 'pirate_captain',
    size: 2.2,
    color: '#e11d48',
    goldMin: 250,
    goldMax: 700,
    lootTable: [
      { defId: 'arbalest_royal', chance: 0.35, minCount: 1, maxCount: 1 },
      { defId: 'sword_bright', chance: 0.4, minCount: 1, maxCount: 1 },
      { defId: 'shield_guardian', chance: 0.4, minCount: 1, maxCount: 1 },
      { defId: 'amulet_platinum', chance: 0.5, minCount: 1, maxCount: 1 },
      { defId: 'potion_strong_health', chance: 1.0, minCount: 3, maxCount: 6 },
    ],
    spells: [
      { name: 'Cannonball Barrage', chance: 0.3, damage: 95, color: '#f97316', isAoe: true },
      { name: 'Cutlass Fury', chance: 0.25, damage: 75, color: '#fb7185' },
    ],
  },

  // --- HUNT 4: DRAGON LAIR ---
  dragon_hatchling: {
    id: 'dragon_hatchling',
    name: 'Dragon Hatchling',
    maxHp: 380,
    attack: 58,
    defense: 26,
    armor: 14,
    speed: 2.2,
    exp: 240,
    modelType: 'dragon',
    size: 1.2,
    color: '#16a34a',
    goldMin: 40,
    goldMax: 110,
    lootTable: [
      { defId: 'val_rotworm_meat', chance: 0.8, minCount: 2, maxCount: 4 },
      { defId: 'shield_dwarven', chance: 0.25, minCount: 1, maxCount: 1 },
      { defId: 'potion_strong_health', chance: 0.35, minCount: 1, maxCount: 2 },
    ],
    spells: [
      { name: 'Mini Fireball', chance: 0.25, damage: 45, color: '#ea580c' },
    ],
  },
  dragon: {
    id: 'dragon',
    name: 'Dragon',
    maxHp: 850,
    attack: 92,
    defense: 40,
    armor: 24,
    speed: 2.0,
    exp: 600,
    modelType: 'dragon',
    size: 2.0,
    color: '#15803d',
    goldMin: 90,
    goldMax: 240,
    lootTable: [
      { defId: 'sword_fire', chance: 0.2, minCount: 1, maxCount: 1 },
      { defId: 'shield_guardian', chance: 0.3, minCount: 1, maxCount: 1 },
      { defId: 'wand_cosmic', chance: 0.25, minCount: 1, maxCount: 1 },
      { defId: 'potion_strong_health', chance: 0.6, minCount: 2, maxCount: 4 },
    ],
    spells: [
      { name: 'Fire Wave', chance: 0.3, damage: 85, color: '#f97316', isAoe: true },
      { name: 'Dragon Fireball', chance: 0.25, damage: 65, color: '#ea580c' },
    ],
  },
  dragon_lord: {
    id: 'dragon_lord',
    name: 'Dragon Lord',
    maxHp: 3800,
    attack: 145,
    defense: 58,
    armor: 32,
    speed: 2.15,
    exp: 2800,
    isBoss: true,
    modelType: 'dragon_lord',
    size: 2.8,
    color: '#dc2626',
    goldMin: 450,
    goldMax: 1200,
    lootTable: [
      { defId: 'sword_fire', chance: 0.6, minCount: 1, maxCount: 1 },
      { defId: 'armor_magic_plate', chance: 0.35, minCount: 1, maxCount: 1 },
      { defId: 'shield_demon', chance: 0.4, minCount: 1, maxCount: 1 },
      { defId: 'boots_haste', chance: 0.45, minCount: 1, maxCount: 1 },
      { defId: 'ring_life', chance: 0.6, minCount: 1, maxCount: 1 },
      { defId: 'potion_strong_health', chance: 1.0, minCount: 4, maxCount: 8 },
    ],
    spells: [
      { name: 'Great Fire Wave', chance: 0.35, damage: 135, color: '#ef4444', isAoe: true },
      { name: 'Explosive Fireball', chance: 0.3, damage: 105, color: '#f97316' },
    ],
  },

  // --- HUNT 5: HERO CAVE ---
  priestess: {
    id: 'priestess',
    name: 'Priestess',
    maxHp: 460,
    attack: 62,
    defense: 28,
    armor: 14,
    speed: 1.95,
    exp: 360,
    modelType: 'hero',
    size: 1.0,
    color: '#a855f7',
    goldMin: 60,
    goldMax: 180,
    lootTable: [
      { defId: 'rod_northwind', chance: 0.3, minCount: 1, maxCount: 1 },
      { defId: 'wand_cosmic', chance: 0.3, minCount: 1, maxCount: 1 },
      { defId: 'potion_mana', chance: 0.7, minCount: 2, maxCount: 4 },
    ],
    spells: [
      { name: 'Dark Hymn', chance: 0.28, damage: 70, color: '#9333ea' },
      { name: 'Unholy Smite', chance: 0.22, damage: 60, color: '#c084fc' },
    ],
  },
  black_knight: {
    id: 'black_knight',
    name: 'Black Knight',
    maxHp: 1100,
    attack: 115,
    defense: 52,
    armor: 30,
    speed: 2.1,
    exp: 850,
    modelType: 'black_knight',
    size: 1.3,
    color: '#18181b',
    goldMin: 120,
    goldMax: 320,
    lootTable: [
      { defId: 'sword_bright', chance: 0.3, minCount: 1, maxCount: 1 },
      { defId: 'armor_plate', chance: 0.4, minCount: 1, maxCount: 1 },
      { defId: 'helmet_crusader', chance: 0.35, minCount: 1, maxCount: 1 },
      { defId: 'shield_guardian', chance: 0.35, minCount: 1, maxCount: 1 },
      { defId: 'potion_strong_health', chance: 0.7, minCount: 2, maxCount: 4 },
    ],
    spells: [
      { name: 'Dark Slash', chance: 0.25, damage: 85, color: '#581c87' },
    ],
  },
  hero_champion: {
    id: 'hero_champion',
    name: 'Hero Champion',
    maxHp: 4400,
    attack: 165,
    defense: 65,
    armor: 38,
    speed: 2.2,
    exp: 3400,
    isBoss: true,
    modelType: 'hero_champion',
    size: 2.3,
    color: '#f59e0b',
    goldMin: 550,
    goldMax: 1500,
    lootTable: [
      { defId: 'sword_fire', chance: 0.5, minCount: 1, maxCount: 1 },
      { defId: 'armor_magic_plate', chance: 0.4, minCount: 1, maxCount: 1 },
      { defId: 'shield_demon', chance: 0.45, minCount: 1, maxCount: 1 },
      { defId: 'amulet_platinum', chance: 0.7, minCount: 1, maxCount: 1 },
      { defId: 'boots_haste', chance: 0.5, minCount: 1, maxCount: 1 },
      { defId: 'potion_strong_health', chance: 1.0, minCount: 4, maxCount: 8 },
    ],
    spells: [
      { name: 'Exori Gran', chance: 0.35, damage: 145, color: '#f59e0b', isAoe: true },
      { name: 'Divine Arrow', chance: 0.28, damage: 110, color: '#fef08a' },
    ],
  },

  // --- HUNT 6: DEMON HELL ---
  fire_devil: {
    id: 'fire_devil',
    name: 'Fire Devil',
    maxHp: 580,
    attack: 85,
    defense: 32,
    armor: 16,
    speed: 2.25,
    exp: 480,
    modelType: 'demon',
    size: 1.2,
    color: '#ea580c',
    goldMin: 80,
    goldMax: 220,
    lootTable: [
      { defId: 'wand_cosmic', chance: 0.3, minCount: 1, maxCount: 1 },
      { defId: 'potion_mana', chance: 0.8, minCount: 2, maxCount: 5 },
    ],
    spells: [
      { name: 'Hellfire Burst', chance: 0.3, damage: 85, color: '#f97316' },
    ],
  },
  behemoth: {
    id: 'behemoth',
    name: 'Behemoth',
    maxHp: 1850,
    attack: 155,
    defense: 60,
    armor: 36,
    speed: 1.9,
    exp: 1600,
    modelType: 'behemoth',
    size: 2.2,
    color: '#713f12',
    goldMin: 180,
    goldMax: 480,
    lootTable: [
      { defId: 'sword_fire', chance: 0.35, minCount: 1, maxCount: 1 },
      { defId: 'shield_demon', chance: 0.3, minCount: 1, maxCount: 1 },
      { defId: 'armor_magic_plate', chance: 0.25, minCount: 1, maxCount: 1 },
      { defId: 'potion_strong_health', chance: 0.8, minCount: 3, maxCount: 6 },
    ],
    spells: [
      { name: 'Ground Shockwave', chance: 0.3, damage: 125, color: '#854d0e', isAoe: true },
      { name: 'Titan Punch', chance: 0.25, damage: 140, color: '#a16207' },
    ],
  },
  demon_overlord: {
    id: 'demon_overlord',
    name: 'Demon Overlord',
    maxHp: 6500,
    attack: 210,
    defense: 75,
    armor: 48,
    speed: 2.15,
    exp: 5800,
    isBoss: true,
    modelType: 'demon_overlord',
    size: 3.2,
    color: '#b91c1c',
    goldMin: 800,
    goldMax: 2500,
    lootTable: [
      { defId: 'armor_magic_plate', chance: 0.55, minCount: 1, maxCount: 1 },
      { defId: 'shield_demon', chance: 0.6, minCount: 1, maxCount: 1 },
      { defId: 'sword_fire', chance: 0.65, minCount: 1, maxCount: 1 },
      { defId: 'arbalest_royal', chance: 0.5, minCount: 1, maxCount: 1 },
      { defId: 'boots_haste', chance: 0.6, minCount: 1, maxCount: 1 },
      { defId: 'ring_life', chance: 0.8, minCount: 1, maxCount: 1 },
      { defId: 'amulet_platinum', chance: 0.9, minCount: 1, maxCount: 1 },
      { defId: 'potion_strong_health', chance: 1.0, minCount: 6, maxCount: 12 },
    ],
    spells: [
      { name: 'Apocalypse Meteor', chance: 0.4, damage: 185, color: '#ef4444', isAoe: true },
      { name: 'Energy Beam', chance: 0.35, damage: 155, color: '#38bdf8' },
      { name: 'Hellfire Drain', chance: 0.25, damage: 130, color: '#dc2626' },
    ],
  },

  // ==========================================
  // WORLD BOSSES & RIFT GUARDIANS
  // ==========================================
  morgaroth_lord: {
    id: 'morgaroth_lord',
    name: 'Morgaroth, o Arquiteto do Pavor',
    maxHp: 28000,
    attack: 340,
    defense: 120,
    armor: 70,
    speed: 2.2,
    exp: 25000,
    isBoss: true,
    modelType: 'demon_overlord',
    size: 4.2,
    color: '#991b1b',
    goldMin: 3500,
    goldMax: 12000,
    lootTable: [
      { defId: 'armor_magic_plate', chance: 0.85, minCount: 1, maxCount: 2 },
      { defId: 'shield_demon', chance: 0.9, minCount: 1, maxCount: 2 },
      { defId: 'sword_fire', chance: 0.95, minCount: 1, maxCount: 2 },
      { defId: 'arbalest_royal', chance: 0.8, minCount: 1, maxCount: 2 },
      { defId: 'boots_haste', chance: 0.9, minCount: 1, maxCount: 2 },
      { defId: 'ring_life', chance: 1.0, minCount: 2, maxCount: 4 },
      { defId: 'amulet_platinum', chance: 1.0, minCount: 2, maxCount: 4 },
    ],
    spells: [
      { name: 'Meteoro Infernal Telegrafado', chance: 0.45, damage: 290, color: '#ef4444', isAoe: true },
      { name: 'Onda Sísmica de Devastação', chance: 0.35, damage: 240, color: '#f59e0b', isAoe: true },
      { name: 'Dreno de Alma Abissal', chance: 0.3, damage: 190, color: '#a855f7' },
    ],
  },
  ghazbaran_frozen: {
    id: 'ghazbaran_frozen',
    name: 'Ghazbaran, o Demônio dos Gelos',
    maxHp: 38000,
    attack: 420,
    defense: 140,
    armor: 85,
    speed: 2.3,
    exp: 40000,
    isBoss: true,
    modelType: 'demon_overlord',
    size: 4.5,
    color: '#0284c7',
    goldMin: 6000,
    goldMax: 18000,
    lootTable: [
      { defId: 'armor_magic_plate', chance: 1.0, minCount: 1, maxCount: 2 },
      { defId: 'shield_demon', chance: 1.0, minCount: 1, maxCount: 2 },
      { defId: 'boots_haste', chance: 1.0, minCount: 2, maxCount: 3 },
      { defId: 'ring_life', chance: 1.0, minCount: 3, maxCount: 5 },
    ],
    spells: [
      { name: 'Ventania de Gelo Absoluto', chance: 0.45, damage: 360, color: '#38bdf8', isAoe: true },
      { name: 'Estilhaço Glacial Telegrafado', chance: 0.4, damage: 310, color: '#0ea5e9' },
      { name: 'Nova de Congelamento', chance: 0.3, damage: 260, color: '#7dd3fc', isAoe: true },
    ],
  },
  ferumbras_ascendant: {
    id: 'ferumbras_ascendant',
    name: 'Ferumbras Ascendente',
    maxHp: 65000,
    attack: 520,
    defense: 180,
    armor: 110,
    speed: 2.4,
    exp: 80000,
    isBoss: true,
    modelType: 'hero_champion',
    size: 4.8,
    color: '#7c3aed',
    goldMin: 12000,
    goldMax: 35000,
    lootTable: [
      { defId: 'wand_cosmic', chance: 1.0, minCount: 2, maxCount: 3 },
      { defId: 'armor_magic_plate', chance: 1.0, minCount: 2, maxCount: 3 },
      { defId: 'shield_demon', chance: 1.0, minCount: 2, maxCount: 3 },
      { defId: 'boots_haste', chance: 1.0, minCount: 3, maxCount: 4 },
    ],
    spells: [
      { name: 'Tempestade Elétrica Apocalíptica', chance: 0.5, damage: 450, color: '#a855f7', isAoe: true },
      { name: 'Raio Cósmico Concentrado', chance: 0.4, damage: 410, color: '#c084fc' },
      { name: 'Barreira Arcana de Chamas Negras', chance: 0.35, damage: 320, color: '#6b21a8', isAoe: true },
    ],
  },

  // TRAINING DUMMY (Interactive dummy in Thais cathedral for ranged/melee DPS testing)
  training_dummy: {
    id: 'training_dummy',
    name: 'Boneco de Treino',
    maxHp: 999999,
    attack: 0,
    defense: 4,
    armor: 2,
    speed: 0,
    exp: 0,
    modelType: 'training_dummy',
    size: 1.1,
    color: '#ca8a04',
    goldMin: 0,
    goldMax: 0,
    lootTable: [],
  },
};

