import { SpellDef } from '../types/game';

export const SPELLS_DATABASE: Record<string, SpellDef> = {
  // --- HEALING ---
  exura: {
    id: 'exura',
    name: 'Light Healing',
    words: 'Exura',
    vocation: ['PALADIN', 'SORCERER', 'DRUID'],
    minLevel: 1,
    minMagicLevel: 1,
    manaCost: 20,
    cooldownMs: 1000,
    range: 0,
    isHeal: true,
    basePower: 35,
    element: 'healing',
    color: '#34d399',
    description: 'Casts a gentle healing aura, recovering moderate health.',
  },
  exura_gran: {
    id: 'exura_gran',
    name: 'Intense Healing',
    words: 'Exura Gran',
    vocation: ['DRUID', 'SORCERER', 'PALADIN'],
    minLevel: 11,
    minMagicLevel: 4,
    manaCost: 70,
    cooldownMs: 1200,
    range: 0,
    isHeal: true,
    basePower: 120,
    element: 'healing',
    color: '#10b981',
    description: 'A powerful surge of divine life that heals severe wounds.',
  },
  exura_vita: {
    id: 'exura_vita',
    name: 'Ultimate Healing',
    words: 'Exura Vita',
    vocation: ['DRUID', 'SORCERER'],
    minLevel: 20,
    minMagicLevel: 8,
    manaCost: 160,
    cooldownMs: 1500,
    range: 0,
    isHeal: true,
    basePower: 380,
    element: 'healing',
    color: '#059669',
    description: 'The supreme healing incantation, restoring nearly all health.',
  },
  exura_ico: {
    id: 'exura_ico',
    name: 'Wound Cleansing',
    words: 'Exura Ico',
    vocation: ['KNIGHT'],
    minLevel: 1,
    minMagicLevel: 0,
    manaCost: 40,
    cooldownMs: 1000,
    range: 0,
    isHeal: true,
    basePower: 65,
    element: 'healing',
    color: '#f59e0b',
    description: 'Knightly physical discipline to staunch bleeding and bandage wounds.',
  },

  // --- KNIGHT ATTACKS ---
  exori_ico: {
    id: 'exori_ico',
    name: 'Brutal Strike',
    words: 'Exori Ico',
    vocation: ['KNIGHT'],
    minLevel: 1,
    minMagicLevel: 0,
    manaCost: 30,
    cooldownMs: 2000,
    range: 1.5,
    basePower: 45,
    element: 'physical',
    color: '#ef4444',
    description: 'A brutal overhead weapon slam that crushes monster armor.',
  },
  exori: {
    id: 'exori',
    name: 'Berserk',
    words: 'Exori',
    vocation: ['KNIGHT'],
    minLevel: 15,
    minMagicLevel: 2,
    manaCost: 115,
    cooldownMs: 4000,
    range: 2.2,
    isAoe: true,
    basePower: 110,
    element: 'physical',
    color: '#dc2626',
    description: 'Whirlwind weapon cleave damaging all surrounding enemies in a circle.',
  },

  // --- PALADIN ATTACKS ---
  exori_san: {
    id: 'exori_san',
    name: 'Divine Caldera',
    words: 'Exori San',
    vocation: ['PALADIN'],
    minLevel: 1,
    minMagicLevel: 1,
    manaCost: 35,
    cooldownMs: 2000,
    range: 4.5,
    basePower: 55,
    element: 'holy',
    color: '#facc15',
    description: 'Empowers arrows/bolts with scorching radiant holy light.',
  },
  exevo_mas_san: {
    id: 'exevo_mas_san',
    name: 'Divine Wrath',
    words: 'Exevo Mas San',
    vocation: ['PALADIN'],
    minLevel: 18,
    minMagicLevel: 5,
    manaCost: 160,
    cooldownMs: 4000,
    range: 3.5,
    isAoe: true,
    basePower: 140,
    element: 'holy',
    color: '#fbbf24',
    description: 'Unleashes a blinding nova of holy arrows striking all nearby foes.',
  },

  // --- SORCERER ATTACKS ---
  exori_vis: {
    id: 'exori_vis',
    name: 'Energy Strike',
    words: 'Exori Vis',
    vocation: ['SORCERER'],
    minLevel: 1,
    minMagicLevel: 1,
    manaCost: 20,
    cooldownMs: 1500,
    range: 3.5,
    basePower: 60,
    element: 'energy',
    color: '#38bdf8',
    description: 'Hurls a sharp shock of electrical energy directly at the target.',
  },
  exevo_vis_lux: {
    id: 'exevo_vis_lux',
    name: 'Energy Beam',
    words: 'Exevo Vis Lux',
    vocation: ['SORCERER'],
    minLevel: 14,
    minMagicLevel: 5,
    manaCost: 110,
    cooldownMs: 3500,
    range: 5.0,
    isAoe: true,
    basePower: 130,
    element: 'energy',
    color: '#60a5fa',
    description: 'A searing beam of concentrated lightning piercing in a straight line.',
  },
  exevo_gran_mas_vis: {
    id: 'exevo_gran_mas_vis',
    name: "Rage of the Skies",
    words: 'Exevo Gran Mas Vis',
    vocation: ['SORCERER'],
    minLevel: 25,
    minMagicLevel: 10,
    manaCost: 250,
    cooldownMs: 8000,
    range: 4.5,
    isAoe: true,
    basePower: 260,
    element: 'energy',
    color: '#818cf8',
    description: 'The legendary ultimate sorcerer spell: summons roaring sky storms.',
  },

  // --- DRUID ATTACKS ---
  exori_frigo: {
    id: 'exori_frigo',
    name: 'Ice Strike',
    words: 'Exori Frigo',
    vocation: ['DRUID'],
    minLevel: 1,
    minMagicLevel: 1,
    manaCost: 20,
    cooldownMs: 1500,
    range: 3.5,
    basePower: 55,
    element: 'ice',
    color: '#06b6d4',
    description: 'Fires a sharp icicle shard that chills the enemy to the bone.',
  },
  exevo_tera_hur: {
    id: 'exevo_tera_hur',
    name: 'Earth Wave',
    words: 'Exevo Tera Hur',
    vocation: ['DRUID'],
    minLevel: 15,
    minMagicLevel: 5,
    manaCost: 120,
    cooldownMs: 3500,
    range: 4.0,
    isAoe: true,
    basePower: 125,
    element: 'earth',
    color: '#84cc16',
    description: 'Violent tremor rolling across the ground crushing all opponents.',
  },

  // --- CLASSIC RUNES ---
  rune_sd: {
    id: 'rune_sd',
    name: 'Sudden Death (SD)',
    words: 'Adori Vita Vis',
    vocation: ['SORCERER', 'DRUID', 'PALADIN', 'KNIGHT'],
    minLevel: 15,
    minMagicLevel: 5,
    manaCost: 0,
    cooldownMs: 2000,
    range: 6.0,
    isRune: true,
    basePower: 340,
    element: 'energy',
    color: '#c084fc',
    description: 'The supreme lethal rune: invokes a malevolent skull projectile dealing catastrophic death damage.',
  },
  rune_gfb: {
    id: 'rune_gfb',
    name: 'Great Fireball (GFB)',
    words: 'Adori Flam',
    vocation: ['SORCERER', 'DRUID', 'PALADIN', 'KNIGHT'],
    minLevel: 10,
    minMagicLevel: 3,
    manaCost: 0,
    cooldownMs: 1800,
    range: 5.5,
    isAoe: true,
    isRune: true,
    basePower: 175,
    element: 'fire',
    color: '#f97316',
    description: 'Explodes a colossal blast of fire in an area, incinerating hordes of foes and igniting the ground.',
  },
  rune_hmm: {
    id: 'rune_hmm',
    name: 'Heavy Magic Missile (HMM)',
    words: 'Adori Vis',
    vocation: ['SORCERER', 'DRUID', 'PALADIN', 'KNIGHT'],
    minLevel: 5,
    minMagicLevel: 1,
    manaCost: 0,
    cooldownMs: 1100,
    range: 6.0,
    isRune: true,
    basePower: 110,
    element: 'energy',
    color: '#38bdf8',
    description: 'Fires high-velocity blue magical bolts with rapid recharge and consistent force.',
  },
  rune_uh: {
    id: 'rune_uh',
    name: 'Ultimate Healing Rune (UH)',
    words: 'Adura Vita',
    vocation: ['SORCERER', 'DRUID', 'PALADIN', 'KNIGHT'],
    minLevel: 8,
    minMagicLevel: 2,
    manaCost: 0,
    cooldownMs: 1500,
    range: 0,
    isHeal: true,
    isRune: true,
    basePower: 420,
    element: 'healing',
    color: '#22c55e',
    description: 'Infuses vital essence to restore near-complete health instantaneously.',
  },
  utevo_lux: {
    id: 'utevo_lux',
    name: 'Light',
    words: 'Utevo Lux',
    vocation: ['SORCERER', 'DRUID', 'PALADIN', 'KNIGHT'],
    minLevel: 8,
    minMagicLevel: 1,
    manaCost: 20,
    cooldownMs: 2000,
    range: 0,
    isHeal: false,
    basePower: 0,
    element: 'holy',
    color: '#fffae0',
    description: 'Invokes a starlight flare singularity with anamorphic diffraction spikes and ambient stardust illumination (4-5 sqm radius).',
  },
  utevo_gran_lux: {
    id: 'utevo_gran_lux',
    name: 'Great Light',
    words: 'Utevo Gran Lux',
    vocation: ['SORCERER', 'DRUID', 'PALADIN', 'KNIGHT'],
    minLevel: 13,
    minMagicLevel: 3,
    manaCost: 60,
    cooldownMs: 3000,
    range: 0,
    isHeal: false,
    basePower: 0,
    element: 'holy',
    color: '#fff8db',
    description: 'Summons a celestial supernova starlight flare with expanded cosmic illumination and dense ambient stardust drift field (~8-10 sqm radius).',
  },
};
